### ISSUE TITLE
3.7.0 Character encoding issues in Firefox 65

### ISSUE THREAD

**Issue by kmaris** [stain/jena-docker#19]
Running the container works, but the html pages (index, manage, etc) all lack character encoding and Firefox does not like that. Chromium seems to ignore it.

<img width="1243" alt="screen shot 2019-01-30 at 10 20 20 am" src="https://user-images.githubusercontent.com/15710405/52001064-c703c080-247b-11e9-9e2b-233d2d573ee8.png">

Adding meta declarations should fix it up (UTF-8 is an example, I'm not sure which to use):

```
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">
<meta charset="UTF-8">
```

I'm not sure if this is an issue with the docker image or the project itself but I figured I'd start here.

**Comment by stain** [comment]
Hi, how did you make the datasets, in the UI, command line or API?

I tried with 3.10.0, which in the UI with Firefox seem to make the datasets and shows them correctly; and it does correct IRI decoding according to the console.

![tdb2-unicode](https://user-images.githubusercontent.com/253413/54354512-be8fcf80-464e-11e9-8638-4e83d26b739c.png)

```
[2019-03-14 11:43:44] Admin      INFO  [100] GET http://localhost:3030/$/stats/tdb-%F0%9F%98%80%E2%9B%94%F0%9F%97%84%F0%9F%94%92-chinese-%E5%AD%94%E5%AD%90
[2019-03-14 11:43:44] Admin      INFO  [100] GET stats dataset /tdb-😀⛔🗄🔒-chinese-孔子
[2019-03-14 11:43:44] Admin      INFO  [100] 200 OK (2 ms)


[2019-03-14 11:43:52] Admin      INFO  [106] GET http://localhost:3030/$/stats/%E5%AD%94%E5%AD%90
[2019-03-14 11:43:52] Admin      INFO  [106] GET stats dataset /孔子
[2019-03-14 11:43:52] Admin      INFO  [106] 200 OK (1 ms)
```

However any kind of interactions, like uploading a ttl file does not work as the dataset resources lke http://localhost:3030/%E5%AD%94%E5%AD%90/get return `404 Not Found`

I guess something is not decoded correctly when mapping to file system? The files are correctly created when viewed in an UTF-8 terminal.

```
(base) stain@biggie:~$ docker exec -it suspicious_fermi ls /fuseki/databases
tdb-😀⛔🗄🔒-chinese-孔子   tdb2-😀⛔🗄🔒-chinese-孔子
```

This docker image seem to have set the correct locale for UTF8

```
(base) stain@biggie:~$ docker exec -it suspicious_fermi bash
bash-4.3# echo $LANG
C.UTF-8
```

So I would suspect this issue is in Fuseki itself, could you raise it on https://issues.apache.org/jira/projects/JENA/ or https://lists.apache.org/list.html?dev@jena.apache.org according to http://jena.apache.org/help_and_support/index.html ? Feel free to refer to this bug.
